export default {
  // create
  POST_CREATE: 'POST_CREATE',
  POST_CREATE_REQUEST: 'POST_CREATE_REQUEST',
  POST_CREATE_SUCCESS: 'POST_CREATE_SUCCESS',
  POST_CREATE_FAILURE: 'POST_CREATE_FAILURE',

  // home
  POST_HOME: 'POST_HOME',
  POST_HOME_REQUEST: 'POST_HOME_REQUEST',
  POST_HOME_SUCCESS: 'POST_HOME_SUCCESS',
  POST_HOME_FAILURE: 'POST_HOME_FAILURE',
};
